export const textStyles = {
  "logo-large": {
    fontFamily: "Monoton",
    fontSize: ["48px", "72px"],
    fontWeight: "normal",
    textTransform: "uppercase",
  },
  "logo-small": {
    fontFamily: "Monoton",
    fontSize: ["32px"],
    fontWeight: "normal",
    textTransform: "uppercase",
  },
  button: {
    fontFamily: "Roboto",
    fontSize: ["16px"],
    fontWeight: "bold",
    letterSpacing: "3%",
    textTransform: "uppercase",
  },
  h2: {
    fontFamily: "Roboto",
    fontSize: ["42px"],
    fontWeight: "bold",
    letterSpacing: "-2%",
    textTransform: "uppercase",
  },
  h3: {
    fontFamily: "Roboto",
    fontSize: ["26px"],
    fontWeight: "bold",
    letterSpacing: "-2%",
    textTransform: "uppercase",
  },
  body: {
    fontFamily: "Roboto",
    fontSize: ["16px"],
    fontWeight: "normal",
    lineHeight: "140%",
  },
  "body-bold": {
    fontFamily: "Roboto",
    fontSize: ["16px"],
    fontWeight: "bold",
    lineHeight: "140%",
  },
  small: {
    fontFamily: "Roboto",
    fontSize: ["14px"],
    fontWeight: "normal",
  },
  "small-bold": {
    fontFamily: "Roboto",
    fontSize: ["14px"],
    fontWeight: "bold",
  },
  xsmall: {
    fontFamily: "Roboto",
    fontSize: ["10px"],
    fontWeight: "normal",
    letterSpacing: "3%",
  },
  "xsmall-bold": {
    fontFamily: "Roboto",
    fontSize: ["10px"],
    fontWeight: "bold",
    letterSpacing: "3%",
  },
  "body-link": {
    fontFamily: "Roboto",
    fontSize: ["16px"],
    fontWeight: "normal",
    lineHeight: "140%",
  },
};
